// Filename: toontownsymbols.h
// Created by:  drose (18Feb00)
/////////////////////////////////////////////

#ifndef TOONTOWNSYMBOLS_H
#define TOONTOWNSYMBOLS_H

/* See dtoolsymbols.h for a rant on the purpose of this file.  */

#ifdef BUILDING_TOONTOWN
  #define BUILDING_TOONTOWN_PETS
  #define BUILDING_TOONTOWN_DNALOADER
  #define BUILDING_TOONTOWN_TOONTOWNBASE
  #define BUILDING_TOONTOWN_SUIT
#endif

#ifdef BUILDING_TOONTOWN_PETS
  #define EXPCL_TOONTOWN_PETS EXPORT_CLASS
  #define EXPTP_TOONTOWN_PETS EXPORT_TEMPL
#else
  #define EXPCL_TOONTOWN_PETS IMPORT_CLASS
  #define EXPTP_TOONTOWN_PETS IMPORT_TEMPL
#endif

#ifdef BUILDING_TOONTOWN_DNALOADER
  #define EXPCL_TOONTOWN_DNALOADER EXPORT_CLASS
  #define EXPTP_TOONTOWN_DNALOADER EXPORT_TEMPL
#else
  #define EXPCL_TOONTOWN_DNALOADER IMPORT_CLASS
  #define EXPTP_TOONTOWN_DNALOADER IMPORT_TEMPL
#endif

#ifdef BUILDING_TOONTOWN_TOONTOWNBASE
  #define EXPCL_TOONTOWN_TOONTOWNBASE EXPORT_CLASS
  #define EXPTP_TOONTOWN_TOONTOWNBASE EXPORT_TEMPL
#else
  #define EXPCL_TOONTOWN_TOONTOWNBASE IMPORT_CLASS
  #define EXPTP_TOONTOWN_TOONTOWNBASE IMPORT_TEMPL
#endif

#ifdef BUILDING_TOONTOWN_SUIT
  #define EXPCL_TOONTOWN_SUIT EXPORT_CLASS
  #define EXPTP_TOONTOWN_SUIT EXPORT_TEMPL
#else
  #define EXPCL_TOONTOWN_SUIT IMPORT_CLASS
  #define EXPTP_TOONTOWN_SUIT IMPORT_TEMPL
#endif

#endif
